### ISSUE TITLE
DEAULT TEST ACCURACY IS SO LOW

### ISSUE THREAD

**Issue by Dadatata-JZ** [cfchen-duke/ProtoPNet#10]
Hi there, 

I have followed the instruction and intended to reproduce the result. However, after 100 epochs, even though the training accuracy has around 99% but the testing accuracy is never over 1%. Any suggestions or tips? It is quite odd for me. 

Thank you very much.

**Comment by sourabhsugandhi** [comment]
Hi @Dadatata-JZ,

Did you got any idea behind the accuracy part? Even I am also facing this issue.
